final String _imagePath = 'assets/images/';
final String assetAdd = 'assets/images/add.svg';
final String assetEntry = 'assets/images/entry.svg';
final String assetExpenses = 'assets/images/expences_v2.svg';
final String assetRegistraion = 'assets/images/registration.svg';
final String assetSearch = 'assets/images/search.svg';
final String assetView = 'assets/images/view.svg';
final String semiCircles = _imagePath + 'semi_circles_icon.png';
final String locationIcon = _imagePath + 'location_icon.png';
